#Script to deploy on the Render Cloud Platform

name: Node.js CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env: 
        webhook_url: ${{secrets.DEPLOY_HOOK_URL}}
        webhook_secret: ${{secrets.DEPLOY_HOOK__KEY}}
    - name: Install dependencies
      run: npm install
    - name: run server
      run: node index.js &
      
    - name: Run tests
      run: |
        sleep 10
        npx mocha acceptance.spec.js
    
#  - uses: bounceapp/render-action@0.6.0
#    with:
#      render-token: ${{secrets.RENDER_API_KEY}}
#      github-token: ${{ secrets.ACC_TOKEN }} #This is the Github Token
#      service-id: "srv-cglufdpmbg56g40p7f40" #This id is unique for each app
#      retries: 20
#      wait: 16000
#      sleep: 30000
